# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '16 6 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}        
        #stale-issue-message: 'This issue is stale because it has been open for 30 days with no activity.'
        close-issue-message: "This issue was closed because it has been inactive for 10 days since being marked as stale."
        #stale-pr-message: 'This pull request is stale because it has been open for 30 days with no activity.'
        close-pr-message: "This pull request was closed because it has been inactive for 10 days since being marked as stale."
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-before-issue-stale: 30
        days-before-issue-close: 10
        days-before-pr-stale: 30
        days-before-pr-close: 10
        exempt-issue-label: question,bug,enhancement,help wanted
        exempt-pr-labels: help wanted
